
title: Jacob Miller's Homepage
page-top-title: Jacob Miller 
top-section-bg-text: Jacob Miller <br> Graph Visualization
home-subtitle: Jacob Miller
copyright-text: '&copy; Jacob Miller 2024. All Rights Reserved.'
